name: app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - psycopg2
  - flask
  - numpy
  - rmsd
  - scipy
  - tqdm
  - pandas
  - xtb
# dev
  - mypy
  - pre-commit
  - pytest
  - pytest-cov
# interative study (notebooks)
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupytext
  - matplotlib
  - nglview
  # pip
  - pip
  - pip:
    - psycopg2-binary
